---
# Here you can add variables that will be available for all hosts.
region: northeurope
resource_group: BTH-kmom01-MACY16-cd5fec # Change me
domain_name: ml-jsramverkproj.wtf # Change me

root_user: azureuser

vmtags:
    StudentId: "macy16" # Change me


pub_ssh_key_location: '/home/martin/.ssh/azureci.pub' # Change me, your local ssh key!