FROM python:3.6-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . .
COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py k8s.sh ./

RUN python -m venv .venv
RUN .venv/bin/pip3 install --upgrade pip
RUN .venv/bin/pip3 install -r requirements.txt

RUN chmod +x k8s.sh

RUN chown -R microblog:microblog ./
USER microblog

EXPOSE 5000
ENTRYPOINT ["./k8s.sh"]
