---
- name: Docker setup step 1
  apt:
    name: "{{ packages + pip_packages }}"

- name: Installing docker public key to apt
  apt_key:
    id: "{{ docker_key }}"
    url: "{{ docker_url }}"

- name: Configure docker apt
  apt_repository:
    repo: "{{ docker_repo }}"
    update_cache: true

- name: Install pip
  apt:
    name: python3-pip

- name: Docker setup step 2
  pip:
    name: 
      - "docker"
      - "docker-compose"
    executable: pip3

- name: Docker setup step 3
  apt:
    name: "docker-ce"
    state: "present"